// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	errors "mini-social-network/errors"

	mock "github.com/stretchr/testify/mock"

	models "mini-social-network/models"

	serializers "mini-social-network/serializers"
)

// AuthServiceInt is an autogenerated mock type for the AuthServiceInt type
type AuthServiceInt struct {
	mock.Mock
}

// CreateUserWithDetails provides a mock function with given fields: req
func (_m *AuthServiceInt) CreateUserWithDetails(req *serializers.SignUpRequest) (*serializers.SignUpResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserWithDetails")
	}

	var r0 *serializers.SignUpResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*serializers.SignUpRequest) (*serializers.SignUpResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*serializers.SignUpRequest) *serializers.SignUpResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serializers.SignUpResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*serializers.SignUpRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoginHandler provides a mock function with given fields: req
func (_m *AuthServiceInt) LoginHandler(req serializers.LoginRequest) (*serializers.LoginResponse, *errors.APIError) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for LoginHandler")
	}

	var r0 *serializers.LoginResponse
	var r1 *errors.APIError
	if rf, ok := ret.Get(0).(func(serializers.LoginRequest) (*serializers.LoginResponse, *errors.APIError)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(serializers.LoginRequest) *serializers.LoginResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serializers.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(serializers.LoginRequest) *errors.APIError); ok {
		r1 = rf(req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.APIError)
		}
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: user
func (_m *AuthServiceInt) UpdateUser(user *models.User) error {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VerifyUserCredentials provides a mock function with given fields: email, password
func (_m *AuthServiceInt) VerifyUserCredentials(email string, password string) (*models.User, error) {
	ret := _m.Called(email, password)

	if len(ret) == 0 {
		panic("no return value specified for VerifyUserCredentials")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*models.User, error)); ok {
		return rf(email, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) *models.User); ok {
		r0 = rf(email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthServiceInt creates a new instance of AuthServiceInt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthServiceInt(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthServiceInt {
	mock := &AuthServiceInt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
