// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// AuthControllerInt is an autogenerated mock type for the AuthControllerInt type
type AuthControllerInt struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: c
func (_m *AuthControllerInt) CreateUser(c *gin.Context) {
	_m.Called(c)
}

// Login provides a mock function with given fields: c
func (_m *AuthControllerInt) Login(c *gin.Context) {
	_m.Called(c)
}

// Logout provides a mock function with given fields: c
func (_m *AuthControllerInt) Logout(c *gin.Context) {
	_m.Called(c)
}

// NewAuthControllerInt creates a new instance of AuthControllerInt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthControllerInt(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthControllerInt {
	mock := &AuthControllerInt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
