// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	errors "mini-social-network/errors"

	mock "github.com/stretchr/testify/mock"

	serializers "mini-social-network/serializers"
)

// UserServiceInt is an autogenerated mock type for the UserServiceInt type
type UserServiceInt struct {
	mock.Mock
}

// DeleteUserByID provides a mock function with given fields: userID
func (_m *UserServiceInt) DeleteUserByID(userID uint) (*serializers.DeleteUserResponse, *errors.APIError) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserByID")
	}

	var r0 *serializers.DeleteUserResponse
	var r1 *errors.APIError
	if rf, ok := ret.Get(0).(func(uint) (*serializers.DeleteUserResponse, *errors.APIError)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint) *serializers.DeleteUserResponse); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serializers.DeleteUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) *errors.APIError); ok {
		r1 = rf(userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.APIError)
		}
	}

	return r0, r1
}

// FollowUsersByID provides a mock function with given fields: userID, followerIDs
func (_m *UserServiceInt) FollowUsersByID(userID uint, followerIDs []uint) *errors.APIError {
	ret := _m.Called(userID, followerIDs)

	if len(ret) == 0 {
		panic("no return value specified for FollowUsersByID")
	}

	var r0 *errors.APIError
	if rf, ok := ret.Get(0).(func(uint, []uint) *errors.APIError); ok {
		r0 = rf(userID, followerIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*errors.APIError)
		}
	}

	return r0
}

// GetFollowersByID provides a mock function with given fields: userID
func (_m *UserServiceInt) GetFollowersByID(userID uint) ([]serializers.FollowResponse, *errors.APIError) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetFollowersByID")
	}

	var r0 []serializers.FollowResponse
	var r1 *errors.APIError
	if rf, ok := ret.Get(0).(func(uint) ([]serializers.FollowResponse, *errors.APIError)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint) []serializers.FollowResponse); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]serializers.FollowResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) *errors.APIError); ok {
		r1 = rf(userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.APIError)
		}
	}

	return r0, r1
}

// GetFollowing provides a mock function with given fields: userID
func (_m *UserServiceInt) GetFollowing(userID uint) ([]serializers.FollowResponse, *errors.APIError) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetFollowing")
	}

	var r0 []serializers.FollowResponse
	var r1 *errors.APIError
	if rf, ok := ret.Get(0).(func(uint) ([]serializers.FollowResponse, *errors.APIError)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint) []serializers.FollowResponse); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]serializers.FollowResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) *errors.APIError); ok {
		r1 = rf(userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.APIError)
		}
	}

	return r0, r1
}

// GetUserByID provides a mock function with given fields: userID
func (_m *UserServiceInt) GetUserByID(userID uint) (*serializers.GetUserResponse, *errors.APIError) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *serializers.GetUserResponse
	var r1 *errors.APIError
	if rf, ok := ret.Get(0).(func(uint) (*serializers.GetUserResponse, *errors.APIError)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint) *serializers.GetUserResponse); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serializers.GetUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) *errors.APIError); ok {
		r1 = rf(userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.APIError)
		}
	}

	return r0, r1
}

// ListUsers provides a mock function with no fields
func (_m *UserServiceInt) ListUsers() ([]serializers.ListUserResponse, *errors.APIError) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []serializers.ListUserResponse
	var r1 *errors.APIError
	if rf, ok := ret.Get(0).(func() ([]serializers.ListUserResponse, *errors.APIError)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []serializers.ListUserResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]serializers.ListUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() *errors.APIError); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.APIError)
		}
	}

	return r0, r1
}

// UnfollowUsersByID provides a mock function with given fields: userID, followerIDs
func (_m *UserServiceInt) UnfollowUsersByID(userID uint, followerIDs []uint) *errors.APIError {
	ret := _m.Called(userID, followerIDs)

	if len(ret) == 0 {
		panic("no return value specified for UnfollowUsersByID")
	}

	var r0 *errors.APIError
	if rf, ok := ret.Get(0).(func(uint, []uint) *errors.APIError); ok {
		r0 = rf(userID, followerIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*errors.APIError)
		}
	}

	return r0
}

// UpdatePasswordByID provides a mock function with given fields: userID, req
func (_m *UserServiceInt) UpdatePasswordByID(userID uint, req serializers.PasswordRequest) {
	_m.Called(userID, req)
}

// UpdateUserByID provides a mock function with given fields: userID, req
func (_m *UserServiceInt) UpdateUserByID(userID uint, req *serializers.UpdateUserRequest) (*serializers.GetUserResponse, *errors.APIError) {
	ret := _m.Called(userID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserByID")
	}

	var r0 *serializers.GetUserResponse
	var r1 *errors.APIError
	if rf, ok := ret.Get(0).(func(uint, *serializers.UpdateUserRequest) (*serializers.GetUserResponse, *errors.APIError)); ok {
		return rf(userID, req)
	}
	if rf, ok := ret.Get(0).(func(uint, *serializers.UpdateUserRequest) *serializers.GetUserResponse); ok {
		r0 = rf(userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serializers.GetUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, *serializers.UpdateUserRequest) *errors.APIError); ok {
		r1 = rf(userID, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.APIError)
		}
	}

	return r0, r1
}

// checkIfUserExists provides a mock function with given fields: userID
func (_m *UserServiceInt) checkIfUserExists(userID uint) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for checkIfUserExists")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserServiceInt creates a new instance of UserServiceInt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserServiceInt(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserServiceInt {
	mock := &UserServiceInt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
