// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// UserControllerInt is an autogenerated mock type for the UserControllerInt type
type UserControllerInt struct {
	mock.Mock
}

// DeleteUser provides a mock function with given fields: c
func (_m *UserControllerInt) DeleteUser(c *gin.Context) {
	_m.Called(c)
}

// FollowUser provides a mock function with given fields: c
func (_m *UserControllerInt) FollowUser(c *gin.Context) {
	_m.Called(c)
}

// GetFollowers provides a mock function with given fields: c
func (_m *UserControllerInt) GetFollowers(c *gin.Context) {
	_m.Called(c)
}

// GetFollowing provides a mock function with given fields: c
func (_m *UserControllerInt) GetFollowing(c *gin.Context) {
	_m.Called(c)
}

// GetUser provides a mock function with given fields: c
func (_m *UserControllerInt) GetUser(c *gin.Context) {
	_m.Called(c)
}

// ListUser provides a mock function with given fields: c
func (_m *UserControllerInt) ListUser(c *gin.Context) {
	_m.Called(c)
}

// UnfollowUser provides a mock function with given fields: c
func (_m *UserControllerInt) UnfollowUser(c *gin.Context) {
	_m.Called(c)
}

// UpdatePassword provides a mock function with given fields: c
func (_m *UserControllerInt) UpdatePassword(c *gin.Context) {
	_m.Called(c)
}

// UpdateUser provides a mock function with given fields: c
func (_m *UserControllerInt) UpdateUser(c *gin.Context) {
	_m.Called(c)
}

// NewUserControllerInt creates a new instance of UserControllerInt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserControllerInt(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserControllerInt {
	mock := &UserControllerInt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
